name: Exploring Workflow Commands

on:
  workflow_dispatch:
  push:

jobs:
  commands_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "HELLO_VAR=World" >> $GITHUB_ENV

      - name: Show environment variable
        run: echo "Hello, $HELLO_VAR!"

      - name: Grouping log lines
        run: |
          echo "::group::Custom Log Group"
          echo "This is a grouped log line 1"
          echo "line 2"
          echo "line 3"
          echo "::endgroup::"

      - name: Mask a value
        env:
          key: p@$Sw0Rd
        run: |
          echo "Un-Masked key = $key"
          echo "::add-mask::$key"
          echo "Masked key = $key"

      - name: Create a warning
        run: echo "::warning::This is a warning message."

      - name: Create an error annotation
        run: echo "::error file=index.js,line=1::Missing semicolon"

      - name: Set a debug message
        run: echo "::debug::This is a debug message"

      - name: Create a notice annotation
        run: echo "::notice file=src/index.js,line=42::Custom notice message"

      - name: Set an output value
        id: my_output
        run: echo "myOutput=007" >> "$GITHUB_OUTPUT"

      - name: Show the output value
        run: echo "My output value is ${{ steps.my_output.outputs.myOutput }}"

      - name: Job Summary
        run: |
          echo "### Awesome Job Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "## Used Workflow Commands" >> $GITHUB_STEP_SUMMARY
          echo "- Debug >> $GITHUB_STEP_SUMMARY" 
          echo "- Mask >> $GITHUB_STEP_SUMMARY" 
          echo "- Output >> $GITHUB_STEP_SUMMARY" 
          echo "- Variable >> $GITHUB_STEP_SUMMARY"
          echo "- Annotations >> $GITHUB_STEP_SUMMARY" 
          echo "- Logs >> $GITHUB_STEP_SUMMARY"
          echo "- Groups >> $GITHUB_STEP_SUMMARY" 
          echo "- Output: ${{ steps.my_output.outputs.myOutput }}" >> $GITHUB_STEP_SUMMARY
          echo "![KodeKloud](https://gdm-catalog-fmapi-prod.imgix.net/ProductScreenshot/68805dd7-e7db-45b6-a08e-3e16559ad183.png)" >> $GITHUB_STEP_SUMMARY